Add base models
coffilation/backend pull request #1
Opened 2023-02-12 12:12 UTC by xalvaine

2023-02-12 12:31 UTC, rybkin-me requested changes

2023-02-12 12:31 UTC, rybkin-me commented on dots/compilations/models.py
> +    class CompilationType(models.TextChoices):
лучше выносить такие штуки в отдельный enums.py в аппе, не хранить в модели (тк ты будешь это еще в коде вероятно использовать)

2023-02-12 12:31 UTC, rybkin-me commented on dots/compilations/models.py
> +    type = models.CharField(max_length=2, choices=CompilationType.choices, default=CompilationType.PUBLIC)
Раз уж используешь чойсес то зачем тут чарфилд, интеджер будет эффективнее

2023-02-12 12:31 UTC, rybkin-me commented on dots/compilations/models.py
> +    type = models.CharField(max_length=2, choices=CompilationType.choices, default=CompilationType.PUBLIC)
Алсо, лучше поле type не называть, потому что это пересекается со встроенным методом type часто

2023-02-12 12:31 UTC, rybkin-me commented on dots/compilations/models.py
> +    type = models.CharField(max_length=2, choices=CompilationType.choices, default=CompilationType.PUBLIC)
Да и вообще у тебя тут булинфилд is_private напрашивается

2023-02-12 12:31 UTC, rybkin-me commented on dots/compilations/models.py
> +    gradient = models.JSONField()
Что за поле, уточни? Зачем тут жисонфилд

2023-02-12 12:31 UTC, rybkin-me commented on apps/places/models.py
> +    display_name = models.CharField(max_length=1023)
че за 1023.................. (кринж)

2023-02-12 12:31 UTC, rybkin-me commented on apps/places/models.py
> +    category = models.CharField(max_length=255)
Это внутрняя категория или из осм? Если внутренняя то лучше ее вынести в отдельную модель [аппу], проще потом работать будет.

2023-02-12 12:31 UTC, rybkin-me commented on apps/places/models.py
> +    type = models.CharField(max_length=255)
см. типы в компиляциях

2023-02-12 12:31 UTC, rybkin-me commented on apps/places/models.py
> +        unique_together = ['osm_id', 'osm_type', 'category']
Юник_тугезер-переменная это депрекейтед кринж, используй массив [constraints](https://docs.djangoproject.com/en/4.1/ref/models/constraints/)

2023-02-12 12:33 UTC, xalvaine commented on dots/compilations/models.py
> +    gradient = models.JSONField()
Это поле, куда фронты будут кидать инфу о своём градиенте, костыль. Выглядеть будет так: https://backend.test.coffilation.ru/#/collections/CollectionsController_findAll

2023-02-12 12:36 UTC, xalvaine commented on apps/places/models.py
> +    display_name = models.CharField(max_length=1023)
А ты сколько хочешь

2023-02-12 12:37 UTC, xalvaine commented on apps/places/models.py
> +    category = models.CharField(max_length=255)
Это osm, там в Meta три поля в юнике, это всё осм

2023-02-12 12:37 UTC, xalvaine commented on apps/places/models.py
> +    type = models.CharField(max_length=255)
Это осм

2023-02-12 13:01 UTC, xalvaine commented on dots/compilations/models.py
> +    class CompilationType(models.TextChoices):
Чек ниже

2023-02-12 13:01 UTC, xalvaine commented on dots/compilations/models.py
> +    type = models.CharField(max_length=2, choices=CompilationType.choices, default=CompilationType.PUBLIC)
https://github.com/coffilation/backend-python/pull/1/commits/48291f3e90f84962f84dad67da0a93168ec37875#diff-8e04584d7ed7d9dadc06ea4f364be94bb257a23023ba91a16d4261251220324bR7

2023-02-12 13:01 UTC, xalvaine commented on apps/places/models.py
> +        unique_together = ['osm_id', 'osm_type', 'category']
https://github.com/coffilation/backend-python/pull/1/commits/48291f3e90f84962f84dad67da0a93168ec37875#diff-c653e4353319312275e38cd228f25b25fa13cffddf1d9e078ebb5eca993f65ebR17

2023-02-12 13:20 UTC, rybkin-me commented on dots/compilations/models.py
> +    gradient = models.JSONField()
А почему тогда нельзя сделать два чарфилда по шесть символов start_color и end_color, где хранить хексованные цвета?

2023-02-12 13:21 UTC, rybkin-me commented on apps/places/models.py
> +    display_name = models.CharField(max_length=1023)
Да в целом 200 инаф, но непонятно почему именно 1023, а не например 836?

2023-02-12 13:22 UTC, rybkin-me commented on apps/places/models.py
> +    category = models.CharField(max_length=255)
Я бы осм категорию таки вынес в отдельную модель для удобства фильтрации в будущем

2023-02-12 13:22 UTC, rybkin-me commented on apps/places/models.py
> +    type = models.CharField(max_length=255)
Так есть же осм-тайп поле

2023-02-12 13:42 UTC, xalvaine commented on apps/places/models.py
> +    display_name = models.CharField(max_length=1023)
там может быть длинное поле, но вщ есть мысль просто убрать лимит

2023-02-12 13:53 UTC, xalvaine commented on dots/compilations/models.py
> +    gradient = models.JSONField()
Потому что кто-то из мобильщиков не смог в хекс, а в таком виде им очень удобно парсить это поле + там может быть больше двух цветов.

2023-02-12 14:38 UTC, rybkin-me commented on apps/places/models.py
> +    display_name = models.CharField(max_length=1023)
Ну убирать лимит не оч производительно будет. Лучше тогда просто бахни 2000 и забей.

2023-02-12 14:39 UTC, rybkin-me commented on dots/compilations/models.py
> +    gradient = models.JSONField()
Тогда конвертируй на уровне сериалайзера, хранить в базе жсонфилд весьма неэффективно.

2023-02-12 19:40 UTC, rybkin-me requested changes

2023-02-12 19:40 UTC, rybkin-me commented on apps/compilations/models.py
> +    description = models.TextField(max_length=1023)
а зачем тут менять чярфилд на текстфилд........? или макс-ленгтх убери или верни чярфилд

2023-02-12 19:55 UTC, xalvaine commented on apps/places/models.py
> +    type = models.CharField(max_length=255)
Просто забей) Они оба osm)
<img width="215" alt="Screenshot 2023-02-12 at 16 55 43" src="https://user-images.githubusercontent.com/56451791/218315267-54a616ca-9f51-48e4-bccc-4b686260733b.png">

2023-02-12 19:55 UTC, xalvaine commented on apps/places/models.py
> +    category = models.CharField(max_length=255)
Пока я считаю в пизду

2023-02-12 19:55 UTC, xalvaine commented on apps/places/models.py
> +    category = models.CharField(max_length=255)
Как появится запрос - вынесем, мигрируем

2023-02-12 19:55 UTC, xalvaine commented on apps/places/models.py
> +    display_name = models.CharField(max_length=1023)
А, его не убрать) Крч предлагаю оставить 1023, т к поле длинное, в 200 может не влезть

2023-02-12 19:55 UTC, xalvaine commented on apps/places/models.py
> +    display_name = models.CharField(max_length=1023)
https://github.com/coffilation/backend-python/pull/1/commits/8177c576654bbbb651b9d1cc663b7697adc208b3#diff-c653e4353319312275e38cd228f25b25fa13cffddf1d9e078ebb5eca993f65ebR11

2023-02-12 19:55 UTC, xalvaine commented on dots/compilations/models.py
> +    gradient = models.JSONField()
Я сдался и сделал чарфилды под хекс: https://github.com/coffilation/backend-python/pull/1/commits/8177c576654bbbb651b9d1cc663b7697adc208b3#diff-8e04584d7ed7d9dadc06ea4f364be94bb257a23023ba91a16d4261251220324bR11

2023-02-12 19:55 UTC, xalvaine commented on apps/compilations/models.py
> +    description = models.TextField(max_length=1023)
Я хотел поспорить, но не нашёл аргументов(

https://github.com/coffilation/backend-python/pull/1/commits/473145be56987208129a11f681fd7542c093f983

2023-02-12 19:58 UTC, rybkin-me requested changes

2023-02-12 19:58 UTC, rybkin-me commented on apps/places/models.py
> +    category = models.CharField(max_length=255)
ну окей мигрировать задолбаешься но как хочешь

2023-02-12 19:58 UTC, rybkin-me commented on apps/places/models.py
> +    type = models.CharField(max_length=255)
лучше все-таки вынести но ап ту ю, по поводу тайпа я в предыд мр (до двух форс-пушей 😡) писал что название поля тайп не оч удачное тк пересекается с дефолт-методом тайп, лучше что-то типа kind

2023-02-12 20:00 UTC, xalvaine commented on apps/places/models.py
> +    type = models.CharField(max_length=255)
Но это названия полей прямо из osm, я бы не хотел их переименовывать, дабы потом не запутаться

2023-02-13 12:07 UTC, rybkin-me commented
ну 7 знаков в цвете это объективно [кринж] но ладно

2023-02-13 12:07 UTC, merged