[feat] Add views
coffilation/backend pull request #2
Opened 2023-02-18 13:35 UTC by xalvaine

2023-02-18 13:39 UTC, xalvaine commented on apps/compilations/serializers.py
> +    author = serializers.PrimaryKeyRelatedField(read_only=True)
Это я поправлю, тут мне нужен UserSerializer или чот такое на read и id на write, будет два сериалайзера

2023-02-18 13:39 UTC, xalvaine commented on apps/compilations/views.py
> +            return Response(serializer.validated_data['places'])
Хз насколько это ок, в ноде сваггер генерится на основе TS-типов, там окей
Здесь мне нужен лист объектов, чтобы обновлять кеш на фронтах без перезапросов списка точек

2023-02-18 13:59 UTC, xalvaine commented on apps/compilations/serializers.py
> +    author = serializers.PrimaryKeyRelatedField(read_only=True)
https://github.com/coffilation/backend-python/pull/2/commits/0f05d5edb109c38498373fb152a816684dc4d079

2023-02-19 10:54 UTC, rybkin-me requested changes

2023-02-19 10:54 UTC, rybkin-me commented on apps/compilations/models.py
> +    description = models.CharField(max_length=2000, null=True)
лучше еще бланк тру для админки добавить, раз уж ты эту модель там используешь

2023-02-19 10:54 UTC, rybkin-me commented on apps/places/views.py
> +    def get_queryset(self):
можно без функции, просто задать queryset так же, как serializer_class

2023-02-19 10:54 UTC, rybkin-me commented on apps/places/serializers.py
> +class AddressSerializer(serializers.Serializer):
господи ужас какой ладно видимо так надо......

2023-02-19 10:54 UTC, rybkin-me commented on apps/compilations/views.py
> +            compilation.places = serializer.validated_data['places']
не уверен что с m2m так можно, там есть методы типа compilation.places.set() или compilation.places.add

2023-02-19 10:54 UTC, rybkin-me commented on apps/compilations/views.py
> +        else:
елс не нужен можно просто ретерн сразу

2023-02-19 10:54 UTC, rybkin-me commented on apps/compilations/views.py
> +            return Response(serializer.validated_data['places'])
Ну сваггер в твой код не полезет. Используй лучше get_serializer_class и разделяй по экшонам какой использовать.

2023-03-06 12:26 UTC, xalvaine commented on apps/compilations/models.py
> +    description = models.CharField(max_length=2000, null=True)
https://github.com/coffilation/backend-python/pull/2/files#diff-8e04584d7ed7d9dadc06ea4f364be94bb257a23023ba91a16d4261251220324b

2023-03-06 12:27 UTC, xalvaine commented on apps/places/serializers.py
> +class AddressSerializer(serializers.Serializer):
Увы, но ща это только для красивого сваггера используется: https://github.com/coffilation/backend-python/pull/2/files#diff-a15649ed435313b6a8b0b891bee0347e49a694e166e3685f8873bda7ce05784bR62

2023-03-06 12:28 UTC, xalvaine commented on apps/compilations/views.py
> +            compilation.places = serializer.validated_data['places']
Более не актуально

2023-03-06 12:28 UTC, xalvaine commented on apps/compilations/views.py
> +        else:
Done

2023-03-06 12:36 UTC, xalvaine commented on apps/compilations/views.py
> +            return [IsAuthenticated()]
Нужно для того, чтобы достать автора при создании коллекции

2023-03-06 12:36 UTC, xalvaine commented on apps/compilations/views.py
> +            return CompilationPlaceSerializer
Сериализует place_id: number

2023-03-06 12:37 UTC, xalvaine commented on apps/places/views.py
> +    osm_type_to_prefix = {
Хз ок ли тут хранить константы, но я ничего лучше не придумал, в рамках ооп вроде ок, в рамках джанги - не ебу

2023-03-06 12:38 UTC, xalvaine commented on apps/places/views.py
> +    def get_place_object_from_nominatim_place(self, nominatim_place):
Тут я тоже ничего лучше не придумал, если есть лучший способ приведения объекта к нужному виду - перепишу

2023-03-06 12:39 UTC, xalvaine commented on apps/places/views.py
> +            print(e)
Ок?

2023-03-06 12:44 UTC, xalvaine commented on dots/settings.py
> +NOMINATIM_SEARCH_ENDPOINT = ENV['NOMINATIM_SEARCH_ENDPOINT']
Норм? Или лучше сразу через ENV к ним обращаться?

2023-03-07 16:22 UTC, rybkin-me requested changes

2023-03-07 16:22 UTC, rybkin-me commented on apps/compilations/serializers.py
> +        exclude = ('places',)
лучше не эксклюд а наоборот филдс использовать, нагляднее видно какие тут поля

2023-03-07 16:22 UTC, rybkin-me commented on apps/compilations/serializers.py
> +    )
один сериалайзер с двумя полями прям просится

2023-03-07 16:22 UTC, rybkin-me commented on apps/compilations/views.py
> +        return Response(status=204)
а в чем тогда принципиальная разница addplace и addplaces? почему нельзя оставить только addplaces и вызывать с массивом из одного элемента если надо одну точку добавить....?

2023-03-07 16:22 UTC, rybkin-me commented on apps/places/views.py
> +    osm_type_to_prefix = {
лучше в отдельный класс как choices

2023-03-07 16:22 UTC, rybkin-me commented on apps/places/views.py
> +    def get_place_object_from_nominatim_place(self, nominatim_place):
ты просто лат и лон заменяешь на латитуде и лонгитуде? а зачем, если не секрет?

2023-03-07 16:22 UTC, rybkin-me commented on apps/places/views.py
> +            return Response(PlaceSerializer(Place.objects.get(**serializer.data)).data)
я б на всякий добавил проверку на то что может быть несколько плейсов, а то спятисотится

2023-03-07 16:22 UTC, rybkin-me commented on apps/places/views.py
> +                    place_in_orm = Place.objects.create(
если их будет много то лучше использовать bulk_create

2023-03-07 16:22 UTC, rybkin-me commented on apps/places/views.py
> +    def search(self, request):
разница я так понимаю в том что лукап это одна точка а серч это список?

2023-03-07 16:22 UTC, rybkin-me commented on apps/places/views.py
> +                place_in_orm, created = Place.objects.get_or_create(
опять же, лучше bulk_create

2023-03-07 16:22 UTC, rybkin-me commented on dots/settings.py
> +from datetime import timedelta
зачем?

2023-03-07 16:25 UTC, xalvaine commented on apps/places/views.py
> +    def get_place_object_from_nominatim_place(self, nominatim_place):
Не просто, я ещё выкидываю остальные поля, без этого получается тайперрор. Поля по приколу переименовываю, юноу, на фронте понятнее))

2023-03-07 16:25 UTC, xalvaine commented on apps/places/views.py
> +    def search(self, request):
Да

2023-03-11 22:32 UTC, xalvaine commented on apps/places/views.py
> +    osm_type_to_prefix = {
А как он должен выглядеть? Или класс со словарём внутри и одним методом типа get_prefix?

2023-03-11 22:35 UTC, xalvaine commented on apps/places/views.py
> +    def get_queryset(self):
https://github.com/coffilation/backend-python/pull/2/files#diff-fcdc1c6f599480371e5403bf79b3676e6386313aaff0370fc2110b3a86af03cbR14

2023-03-11 22:36 UTC, xalvaine commented on apps/compilations/serializers.py
> +        exclude = ('places',)
https://github.com/coffilation/backend-python/pull/2/files#diff-39bf1ea2e7d8da33c6e08617863b8491ab918a41a14219831639c7fb948ed8d7R15

2023-03-11 22:36 UTC, xalvaine commented on apps/compilations/serializers.py
> +    )
Удалил запросы с одной точкой, более не актуально

2023-03-11 22:37 UTC, xalvaine commented on apps/compilations/views.py
> +        return Response(status=204)
Убрал addplace

2023-03-11 22:38 UTC, xalvaine commented on apps/places/views.py
> +            return Response(PlaceSerializer(Place.objects.get(**serializer.data)).data)
Убрал этот запрос

2023-03-11 22:38 UTC, xalvaine commented on apps/places/views.py
> +                place_in_orm, created = Place.objects.get_or_create(
https://github.com/coffilation/backend-python/pull/2/files#diff-fcdc1c6f599480371e5403bf79b3676e6386313aaff0370fc2110b3a86af03cbR90

2023-03-11 22:38 UTC, xalvaine commented on dots/settings.py
> +from datetime import timedelta
Убрал

2023-03-16 15:38 UTC, rybkin-me requested changes

2023-03-16 15:38 UTC, rybkin-me commented on apps/places/views.py
> +    osm_type_to_prefix = {
как чойсез ролей в компилейшон_мембершип

2023-03-16 15:38 UTC, rybkin-me commented on apps/places/views.py
> +    def get_place_object_from_nominatim_place(self, nominatim_place):
ты можешь просто dict(nomination_place) делать....

2023-03-16 15:38 UTC, rybkin-me commented on apps/places/views.py
> +                    place_in_orm = Place.objects.create(
@xalvaine че делать будем? ты там с айдюками чет вроде начебуровил?

2023-03-16 15:38 UTC, rybkin-me commented on apps/places/views.py
> +    def search(self, request):
просто может вынести как-то ф отдельную функцию часть с получением инфы из номинатима и креатингом точек? а то вайб что оно дублируется. не настаиваю

2023-03-16 15:38 UTC, rybkin-me commented on dots/settings.py
> +NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
```
NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
```

2023-03-16 15:38 UTC, rybkin-me commented on dots/urls.py
> +router.register(r'compilations', CompilationViewSet, 'compilation')
лучше роутер в отдельный файл в эппс вынести, тут все-таки больше системная история а там пусть то что с функционалом вместе лежит

2023-03-16 22:16 UTC, xalvaine commented on apps/places/views.py
> +    def search(self, request):
Я бы оставил пока так

2023-03-16 22:16 UTC, xalvaine commented on apps/places/views.py
> +                    place_in_orm = Place.objects.create(
Это лукап, тут создаётся один элемент, после криейта идёт ретёрн, булк и прочее в сёрче

2023-03-16 22:24 UTC, xalvaine commented on dots/settings.py
> +NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
Предлагаешь просто из env их доставать?

2023-03-16 22:24 UTC, xalvaine commented on apps/places/views.py
> +    def get_place_object_from_nominatim_place(self, nominatim_place):
Буду знать, но тут я бы оставил функцию

2023-03-16 22:28 UTC, xalvaine commented on apps/places/views.py
> +    osm_type_to_prefix = {
А как по id получить value? Типа класс с choices я сделаю, окей, там будет какой-то метод для получения значения choice'a типа `osm_type_to_prefix.some_method(type)`?

2023-03-16 22:30 UTC, xalvaine commented on dots/urls.py
> +router.register(r'compilations', CompilationViewSet, 'compilation')
https://github.com/coffilation/backend-python/pull/2/commits/4c107ef628c6b26840ddade221405806c1071cae

2023-03-17 09:53 UTC, rybkin-me requested changes

2023-03-17 09:53 UTC, rybkin-me commented on dots/settings.py
> +NOMINATIM_LOOKUP_ENDPOINT = ENV['NOMINATIM_LOOKUP_ENDPOINT']
а, мне показалось что тут дважды одинаковое написано пахапххапхап
но вообще os.getenv(), как и в 3 пулле

2023-03-17 09:53 UTC, rybkin-me commented on apps/places/views.py
> +            return Response(PlaceSerializer(Place.objects.get(**serializer.data)).data)
Откуда? Не понял.

2023-03-17 09:53 UTC, rybkin-me commented on apps/places/views.py
> +    def get_place_object_from_nominatim_place(self, nominatim_place):
Зачем?

2023-03-17 09:53 UTC, rybkin-me commented on apps/places/views.py
> +    osm_type_to_prefix = {
https://docs.djangoproject.com/en/4.1/ref/models/instances/#django.db.models.Model.get_FOO_display

2023-03-17 09:53 UTC, rybkin-me commented on apps/compilations/views.py
> +            return [IsAuthenticated()]
лучше не по методу а по экшонам

2023-03-17 10:45 UTC, xalvaine commented on apps/places/views.py
> +    def get_place_object_from_nominatim_place(self, nominatim_place):
Затем, что у меня lat и lon записываются в бд, как latitude и longitude. Или ты сильно за то, чтобы переименовать их в lat и lon?

2023-03-17 11:11 UTC, rybkin-me requested changes

2023-03-17 11:11 UTC, rybkin-me commented on apps/places/views.py
> +    osm_type_to_prefix = {
А, погоди, так для этого можешь OSM_TYPES_PREFIXES[type] наверное взять

2023-03-17 18:55 UTC, rybkin-me submitted a review, later dismissed

2023-03-17 22:29 UTC, rybkin-me approved these changes

2023-03-17 22:30 UTC, merged