Add dockerfile and ci
coffilation/backend pull request #3
Opened 2023-03-12 18:10 UTC by xalvaine

2023-03-16 15:32 UTC, rybkin-me requested changes

2023-03-16 15:32 UTC, rybkin-me commented on dots/settings.py
> +    **dotenv_values(),
че за кринж зачем тебе в джанго все переменные окружения просто сделай лучше где надо 
`os.getenv('ENVNAME')`

2023-03-16 15:32 UTC, rybkin-me commented on dots/settings.py
> +    ENV['DJANGO_ALLOWED_HOST'],
у тебя может быть несколько хостов

2023-03-16 15:32 UTC, rybkin-me commented on dots/settings.py
> +    'VERSION': ENV.get('VERSION', '1.0.0'),
VERSION чего? яблок? пушкиных? переменные нормально называй, тем более если они в окружении

2023-03-16 22:31 UTC, xalvaine commented on dots/settings.py
> +    'VERSION': ENV.get('VERSION', '1.0.0'),
Душнила

2023-03-16 22:42 UTC, xalvaine commented on dots/settings.py
> +    'VERSION': ENV.get('VERSION', '1.0.0'),
https://github.com/coffilation/backend-python/pull/3/commits/adc131811cc525d4122841388547a34d04560396#diff-3f2127450507e60dee6821873a0a0bf1664bd0b1b4a495ffe66025904d3a2d6dR155

2023-03-16 22:43 UTC, xalvaine commented on dots/settings.py
> +    ENV['DJANGO_ALLOWED_HOST'],
https://github.com/coffilation/backend-python/pull/3/commits/adc131811cc525d4122841388547a34d04560396#diff-3f2127450507e60dee6821873a0a0bf1664bd0b1b4a495ffe66025904d3a2d6dR30

2023-03-16 22:43 UTC, xalvaine commented on dots/settings.py
> +    **dotenv_values(),
https://github.com/coffilation/backend-python/pull/3/commits/adc131811cc525d4122841388547a34d04560396

2023-03-17 09:47 UTC, rybkin-me requested changes

2023-03-17 09:47 UTC, rybkin-me commented on dots/settings.py
> +CSRF_TRUSTED_ORIGINS = os.getenv('DJANGO_ALLOWED_ORIGINS').split(','),
во-первых убери в конце обеих переменных запятую, во-вторых тебе незачем два енв-вара для этого делать, у тебя трастед ориджинс скорее всего совпадает с эллауэд хостс

2023-03-17 22:41 UTC, rybkin-me approved these changes

2023-03-17 22:42 UTC, merged