Add authorization
coffilation/backend pull request #4
Opened 2023-03-15 22:45 UTC by xalvaine

2023-03-15 22:46 UTC, xalvaine commented on apps/compilations/views.py
> +    def has_permission(self, request, view):
Бля крч, я не понимаю, как мне нормально сделать проверки типа "я мембер коллекции", "я админ коллекции" и пр.

2023-03-15 22:47 UTC, xalvaine commented on apps/compilations/models.py
> +class CompilationMembershipRole(models.IntegerChoices):
Олсо не нашел способ хранить в бд integer, а возвращать во всез запросах (и принимать) стринги

2023-03-16 15:26 UTC, rybkin-me requested changes

2023-03-16 15:26 UTC, rybkin-me commented on dots/urls.py
> +router.register(
кмк лучше либо все в одну строку либо все в неск

2023-03-16 15:26 UTC, rybkin-me commented on apps/compilations/models.py
> +class CompilationMembershipRole(models.IntegerChoices):
не понял, чего ты хочешь? ты можешь кастомный сериалайзерфилд прописать как вариант.

2023-03-16 15:26 UTC, rybkin-me commented on apps/compilations/serializers.py
> +        fields = ('primary_color', 'secondary_color', 'is_private', 'name', 'description', 'owner')
теперь не ридонли?

2023-03-16 15:26 UTC, rybkin-me commented on apps/compilations/views.py
> +class CompilationMembershipsViewSet(viewsets.ModelViewSet):
я бы в отдельную аппу вынес компилейшонмембершип -- отдельные вьюхи, урлы и сериалайзеры

2023-03-16 15:26 UTC, rybkin-me commented on apps/compilations/views.py
> +    def has_permission(self, request, view):
тогда тебе надо не has_permission а has_object_permission и внутри у тебя есть все что надо (реквест, объект, вьюха)

Пример:
```
    def has_object_permission(self, request, view, obj):
        # Forbid deleting yourself
        return not (view.action == 'destroy' and obj.user == request.user)
```

2023-03-16 15:26 UTC, rybkin-me commented on apps/compilations/views.py
> +from .serializers import *
ну такое...

2023-03-16 15:26 UTC, rybkin-me commented on apps/compilations/views.py
> +    filterset_fields = ['is_private', 'owner', 'places']
какой смысл в фильтре из_прайват если в гет_квоерисет у тебя квоерисет отфильтрованный по из_прайват=фолс

2023-03-16 15:26 UTC, rybkin-me commented on apps/compilations/views.py
> +        if self.request.method in ('POST', 'PATCH'):
лучше по экшонам а не методам

2023-05-14 23:44 UTC, closed without merging